import React, { useState } from "react";
import { context, rows, date, label, Heading, Field, Form, Badge, Empty } from "./ui";

const root = "/admin/education";
const time = value => value ? new Date(value).toLocaleString(undefined, { dateStyle: "medium", timeStyle: "short" }) : "No deadline";
const inputTime = value => {
    if (!value) return "";
    const parts = new Intl.DateTimeFormat("en-CA", { timeZone: "Asia/Karachi", year: "numeric", month: "2-digit", day: "2-digit", hour: "2-digit", minute: "2-digit", hourCycle: "h23" }).formatToParts(new Date(value));
    const get = key => parts.find(part => part.type === key)?.value;
    return `${get("year")}-${get("month")}-${get("day")}T${get("hour")}:${get("minute")}`;
};
function SectionNav({sections}) {return <nav className="learning-section-nav" aria-label="Classroom sections">{sections.map(([id,title])=><a key={id} href={`#${id}`}>{title}</a>)}</nav>;}
export function LearningActivities({enrollment,learning={}}) {
    const [tab,setTab]=useState("schedule");
    if(!["active","completed"].includes(enrollment.status))return null;
    const tabs=[["schedule","Schedule & attendance"],["assignments","Assignments"],["quizzes","Quizzes"]];
    const active=enrollment.status==="active";
    return <section className="panel learning-activities" id="learning-activities"><div className="panel-heading"><h2>Your classroom activities</h2></div><div className="learning-tabs" role="tablist" aria-label="Learning activities">{tabs.map(([id,title])=><button key={id} type="button" role="tab" id={`activity-tab-${id}`} aria-controls={`activity-panel-${id}`} aria-selected={tab===id} onClick={()=>setTab(id)}>{title}</button>)}</div>
    <div role="tabpanel" id={`activity-panel-${tab}`} aria-labelledby={`activity-tab-${tab}`}>
    {tab==="schedule"&&<><AttendanceSummary summary={learning.attendanceSummary}/>{!rows(learning.sessions).length&&<p>Your instructor will publish class sessions here.</p>}<div className="learning-session-list">{rows(learning.sessions).map(s=>{const mark=rows(learning.attendance).find(a=>a.education_session_id===s.id);return <article key={s.id}><div><h3>{s.title}</h3><p>{time(s.starts_at)}</p>{s.notes&&<p className="preserve">{s.notes}</p>}{mark?.note&&<small>Instructor note: {mark.note}</small>}</div><Badge>{mark?.status || (s.status==="completed"?"not_recorded":s.status)}</Badge></article>;})}</div></>}
    {tab==="assignments"&&<>{!rows(learning.assignments).length&&<p>No assignments published yet.</p>}{rows(learning.assignments).map(a=>{const submission=rows(learning.submissions).find(s=>s.education_assignment_id===a.id);const canSubmit=active&&(!submission||["submitted","changes_requested"].includes(submission.status))&&(a.allow_late||!a.due_at||new Date(a.due_at)>=new Date());return <article className="learning-task" key={a.id}><div className="panel-heading"><h3>{a.title}</h3><Badge>{submission?.status||"not_submitted"}</Badge></div><p className="preserve">{a.instructions}</p><div className="learning-task-meta"><span>Due: {time(a.due_at)}</span><span>Pass mark: {a.pass_percent}%</span>{a.is_required&&<strong>Required for certificate</strong>}</div>{submission&&<div className="learning-feedback"><strong>Your submission</strong><p className="preserve">{submission.body}</p>{submission.file_name&&<a href={`/education/submissions/${submission.id}/file`}>Download {submission.file_name} ↗</a>}<p>{submission.is_late&&"Submitted late · "}{time(submission.submitted_at)}{submission.score!==null&&` · Score: ${submission.score}%`}</p>{submission.feedback&&<><strong>Instructor feedback</strong><p className="preserve">{submission.feedback}</p></>}</div>}{canSubmit?<Form action={`/learn/${enrollment.id}/assignments/${a.id}`} submit={submission?"Resubmit assignment":"Submit assignment"}><Field name="body" title="Your answer or project notes" type="textarea" value={submission?.body} maxLength={20000} required/><Field name="file" title="Optional attachment (up to 10 MB)" type="file" accept=".pdf,.txt,.zip,.docx,.jpg,.jpeg,.png"/><small>{a.allow_late?"Late submissions are accepted and marked late.":"Submissions close at the deadline."} An existing attachment is kept unless you upload a replacement.</small></Form>:!submission&&active?<p>Submissions are closed for this assignment.</p>:null}</article>;})}</>}
    {tab==="quizzes"&&<>{!rows(learning.quizzes).length&&<p>No quizzes published yet.</p>}{rows(learning.quizzes).map(q=>{const attempts=rows(learning.attempts).filter(a=>a.education_quiz_id===q.id);const passed=attempts.some(a=>a.passed);return <article className="learning-task" key={q.id}><div className="panel-heading"><h3>{q.title}</h3><Badge>{passed?"passed":"quiz"}</Badge></div><p>{q.instructions}</p><div className="learning-task-meta"><span>{q.questions.length} questions</span><span>Pass mark: {q.pass_percent}%</span><span>{attempts.length} / {q.max_attempts} attempts used</span>{q.is_required&&<strong>Required for certificate</strong>}</div>{attempts.length>0&&<ol className="learning-attempts">{attempts.map(a=><li key={a.attempt_number}>Attempt {a.attempt_number}: <strong>{a.score}%</strong> · {a.passed?"Passed":"Not passed"} · {date(a.created_at)}</li>)}</ol>}{active&&!passed&&attempts.length<q.max_attempts?<Form action={`/learn/${enrollment.id}/quizzes/${q.id}`} submit="Submit quiz" confirm="Submit these answers? This uses one quiz attempt."><input type="hidden" name="attempt_number" value={attempts.length+1}/>{q.questions.map((question,i)=><fieldset className="learning-question" key={i}><legend>{i+1}. {question.prompt}</legend>{question.options.map((option,j)=><label key={j}><input type="radio" name={`answers[${i}]`} value={j} required/><span>{option}</span></label>)}</fieldset>)}</Form>:!passed&&active?<p>You’ve used all available attempts. Contact your instructor for guidance.</p>:null}</article>;})}</>}
    </div></section>;
}
export function AttendanceSummary({summary}) {if(!summary)return null;return <div className="learning-attendance-summary"><strong>{summary.percent===null?"—":`${summary.percent}%`}</strong><div><span>Attendance · {summary.attended} of {summary.counted} counted classes</span><small>{summary.required?`${summary.required}% required for certification. `:"No minimum attendance requirement. "}Present and late count as attended; excused classes are excluded. Completed classes without a mark count as missed.</small></div></div>;}
function SessionFields({session={}}) {return <><Field name="title" title="Session title" value={session.title} required maxLength={255}/><Field name="starts_at" title="Session date and time (Pakistan time)" type="datetime-local" value={inputTime(session.starts_at)} required/><Field name="status" type="select" value={session.status||"scheduled"} options={["scheduled","completed","cancelled"]}/><Field name="notes" title="Class notes (visible to students)" type="textarea" value={session.notes} maxLength={5000}/></>;}
function AssignmentFields({assignment={}}) {return <><Field name="title" title="Assignment title" value={assignment.title} required maxLength={255}/><Field name="instructions" type="textarea" value={assignment.instructions} required maxLength={20000}/><div className="form-grid"><Field name="due_at" title="Deadline (Pakistan time, optional)" type="datetime-local" value={inputTime(assignment.due_at)}/><Field name="pass_percent" title="Pass mark (%)" type="number" min={1} max={100} value={assignment.pass_percent||60} required/></div><Field name="allow_late" title="Accept late submissions" type="checkbox" value={assignment.allow_late??true}/><Field name="is_published" title="Publish to students" type="checkbox" value={assignment.is_published}/><Field name="is_required" title="Passing this assignment is required for certification" type="checkbox" value={assignment.is_required}/></>;}
function QuizFields({quiz={}}) {
    const ownOld=context.old._form_action?.endsWith(quiz.id?`/quizzes/${quiz.id}`:"/quizzes");
    const [questions,setQuestions]=useState(ownOld&&Array.isArray(context.old.questions)?context.old.questions:quiz.questions||[{prompt:"",options:["","","",""],correct:0}]);
    const locked=quiz.attempts_count>0;
    const change=(index,field,value)=>setQuestions(questions.map((q,i)=>i===index?{...q,[field]:value}:q));
    return <><Field name="title" title="Quiz title" value={quiz.title} required maxLength={255}/><Field name="instructions" title="Quiz instructions" type="textarea" value={quiz.instructions} maxLength={10000}/><div className="form-grid"><Field name="pass_percent" title="Pass mark (%)" type="number" min={1} max={100} value={quiz.pass_percent||60} required readOnly={locked}/><Field name="max_attempts" title="Maximum attempts" type="number" min={1} max={10} value={quiz.max_attempts||3} required readOnly={locked}/></div>{locked&&<p>Questions and scoring are locked because students have attempted this quiz. You can change its title, instructions, and visibility.</p>}{questions.map((q,i)=><fieldset className="quiz-author-question" key={i}><legend>Question {i+1}</legend><label className="field"><span>Question text</span><textarea name={`questions[${i}][prompt]`} value={q.prompt} onChange={e=>change(i,"prompt",e.target.value)} required maxLength={2000} readOnly={locked}/></label>{q.options.map((option,j)=><label className="field" key={j}><span>Option {j+1}</span><input name={`questions[${i}][options][${j}]`} value={option} onChange={e=>change(i,"options",q.options.map((o,k)=>k===j?e.target.value:o))} required maxLength={1000} readOnly={locked}/></label>)}<label className="field"><span>Correct answer</span><select name={`questions[${i}][correct]`} value={q.correct} onChange={e=>change(i,"correct",Number(e.target.value))} disabled={locked}>{q.options.map((_,j)=><option key={j} value={j}>Option {j+1}</option>)}</select>{locked&&<input type="hidden" name={`questions[${i}][correct]`} value={q.correct}/>}</label>{!locked&&questions.length>1&&<button type="button" className="text-link" onClick={()=>setQuestions(questions.filter((_,j)=>j!==i))}>Remove question</button>}</fieldset>)}{!locked&&questions.length<50&&<button className="button secondary" type="button" onClick={()=>setQuestions([...questions,{prompt:"",options:["","","",""],correct:0}])}>Add question +</button>}<Field name="is_published" title="Publish quiz" type="checkbox" value={quiz.is_published}/><Field name="is_required" title="Passing this quiz is required for certification" type="checkbox" value={quiz.is_required}/></>;
}
export function BatchClassroom({batch,students,sessions,assignments,quizzes}) {
    const base=`${root}/batches/${batch.id}`;
    const active=students.filter(s=>s.status==="active");
    return <section className="education"><a className="text-link" href={`${root}/courses/${batch.course_id}/edit`}>← Course & batches</a><Heading eyebrow={batch.course.title} title={batch.name} description="Plan classes, record attendance, and assess student learning."/><SectionNav sections={[["class-sessions","Attendance"],["class-assignments","Assignments"],["class-quizzes","Quizzes"]]}/><Form action={`${base}/requirements`} method="PATCH" className="panel education-filters" submit="Save requirement"><Field name="required_attendance_percent" title="Minimum attendance for certification (%) · 0 disables" type="number" min={0} max={100} value={batch.required_attendance_percent||0} required/></Form>
    <section id="class-sessions" className="panel"><h2>Class sessions & attendance</h2><p>Session dates are entered in Pakistan time. Mark a held session completed, then record attendance for active students.</p>{sessions.map(s=><details className="education-lesson" key={s.id} open={context.old._form_action?.includes(`/sessions/${s.id}`)}><summary>{s.title}<Badge>{s.status}</Badge><small>{time(s.starts_at)}</small></summary><Form action={`${base}/sessions/${s.id}`} method="PUT" submit="Save session"><SessionFields session={s}/></Form>{s.status==="completed"&&active.length>0&&<Form action={`${base}/sessions/${s.id}/attendance`} submit="Save attendance" className="attendance-form"><h3>Attendance register</h3>{active.map((student,i)=>{const mark=s.attendance.find(a=>a.course_enrollment_id===student.id);return <div className="attendance-student" key={student.id}><strong>{student.student.name}</strong><input type="hidden" name={`marks[${i}][enrollment_id]`} value={student.id}/><Field name={`marks[${i}][status]`} title="Attendance" type="select" value={mark?.status||""} required options={[{value:"",label:"Choose status"},"present","absent","late","excused"]}/><Field name={`marks[${i}][note]`} title="Note (optional)" value={mark?.note} maxLength={500}/></div>;})}</Form>}{students.filter(student=>student.status==="completed").length>0&&<p>Attendance for completed enrollments is locked.</p>}</details>)}<details className="education-lesson" open={context.old._form_action===`${base}/sessions`}><summary>Add a session +</summary><Form action={`${base}/sessions`} submit="Create session"><SessionFields/></Form></details></section>
    <section id="class-assignments" className="panel"><h2>Assignments & grading</h2>{assignments.map(a=><details className="education-lesson" key={a.id} open={context.old._form_action===`${base}/assignments/${a.id}`}><summary>{a.title}<small>{a.submissions.length} submissions</small></summary><Form action={`${base}/assignments/${a.id}`} method="PUT" submit="Save assignment"><AssignmentFields assignment={a}/></Form>{a.submissions.map(s=><article className="learning-task" key={s.id}><h3>{s.enrollment.student.name}</h3><Badge>{s.status}</Badge><p className="preserve">{s.body}</p><small>Submitted {time(s.submitted_at)}{s.is_late?" · Late":""}</small>{s.file_name&&<p><a href={`/education/submissions/${s.id}/file`}>Download {s.file_name} ↗</a></p>}{s.enrollment.status==="active"?<Form action={`${root}/submissions/${s.id}`} method="PATCH" submit="Save assignment review"><Field name="decision" title="Review action" type="select" options={[{value:"grade",label:"Grade submission"},{value:"request_changes",label:"Request revision"}]}/><Field name="score" title="Score out of 100 (required when grading)" type="number" min={0} max={100} value={s.score}/><Field name="feedback" title="Feedback to student" type="textarea" value={s.feedback} required maxLength={10000}/></Form>:<p>Final score: {s.score??"—"}% · {s.feedback}</p>}</article>)}</details>)}<details className="education-lesson" open={context.old._form_action===`${base}/assignments`}><summary>Add assignment +</summary><Form action={`${base}/assignments`} submit="Create assignment"><AssignmentFields/></Form></details></section>
    <section id="class-quizzes" className="panel"><h2>Quizzes</h2><p>Single-answer multiple-choice questions are graded on the server. Students receive a score without the answer key.</p>{quizzes.map(q=><details className="education-lesson" key={q.id} open={context.old._form_action===`${base}/quizzes/${q.id}`}><summary>{q.title}<small>{q.attempts_count} attempts recorded</small></summary><Form action={`${base}/quizzes/${q.id}`} method="PUT" submit="Save quiz"><QuizFields quiz={q}/></Form></details>)}<details className="education-lesson" open={context.old._form_action===`${base}/quizzes`}><summary>Add quiz +</summary><Form action={`${base}/quizzes`} submit="Create quiz"><QuizFields/></Form></details></section></section>;
}
